version: '3'
services:
  database:
    container_name: "database"
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cloudapi
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USERNAME: root
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
  app:
    container_name: "app"
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      spring_datasource_url: jdbc:mysql://database:3306/cloudapi
      SPRING_LIQUIBASE_URL: jdbc:mysql://database:3306/cloudapi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_LIQUIBASE_USER: root
      SPRING_LIQUIBASE_PASSWORD: mysql







